import pluralize from "pluralize";
import {
  nativeTypeFor,
  renderSqlDefault,
  type ConverterField,
} from "../field-converters/base.ts";
import sqlite from "../field-converters/sqlite.ts";
import mysql from "../field-converters/mysql.ts";
import postgres from "../field-converters/postgres.ts";
import oracle from "../field-converters/oracle.ts";
import sqlserver from "../field-converters/sqlserver.ts";
import { q, type SqlDialect } from "./sql-dialect.ts";

const DIALECT_CONVERTERS = {
  sqlite,
  mysql,
  postgres,
  oracle,
  sqlserver,
} as const;

const effectiveTableName = (name: string, pluralizeFlag: boolean): string => {
  if (!pluralizeFlag || !name) return name;
  const parts = String(name).split("_");
  parts[parts.length - 1] = pluralize(parts[parts.length - 1]);
  return parts.join("_");
};

export type SeedValue = string | number | boolean | null;

export type RawIndexDef = {
  fields: string[];
  is_unique?: boolean;
};

type RawFieldDef = {
  type?: string;
  size?: number;
  is_nullable?: boolean;
  is_unique?: boolean;
  default_value?: SeedValue;
  references?: string;
  primary_key?: boolean;
};

type RawTableDef = {
  fields: Array<Record<string, RawFieldDef>>;
  indexes?: Array<Record<string, RawIndexDef>>;
  seeds?: Array<Record<string, Record<string, SeedValue>>>;
  datasource_type?: string;
  skip_migrations?: boolean;
  use_optimistic_concurrency?: boolean;
};

type RawTableEntry = Record<string, RawTableDef>;

type NormalizedField = ConverterField & {
  name: string;
  isNullable: boolean;
  isUnique: boolean;
  primaryKey: boolean;
  references?: string;
};

type NormalizedTable = {
  name: string;
  entityName: string;
  pluralizeTableNames: boolean;
  datasourceType?: string;
  optimisticConcurrency?: boolean;
  fields: NormalizedField[];
};

export type GenerateTableOptions = {
  idType?: string;
  withUuidColumn?: boolean;
  skipForeignKeys?: boolean;
  useOptimisticConcurrency?: boolean;
  pluralizeTableNames?: boolean;
};

const converterFor = (dialect: string) => {
  const mod = DIALECT_CONVERTERS[dialect as keyof typeof DIALECT_CONVERTERS];
  if (!mod) throw new Error(`Unknown dialect "${dialect}"`);
  return mod;
};

const mapColumnType = (dialect: string, field: ConverterField): string =>
  nativeTypeFor(converterFor(dialect), field);

const ID_COLUMN_SUFFIX: Record<string, Record<SqlDialect, string>> = {
  integer: {
    sqlite: "INTEGER PRIMARY KEY AUTOINCREMENT",
    postgres: "SERIAL PRIMARY KEY",
    sqlserver: "INT IDENTITY(1,1) PRIMARY KEY",
    mysql: "INT AUTO_INCREMENT PRIMARY KEY",
    oracle: "NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  },
  biginteger: {
    sqlite: "INTEGER PRIMARY KEY AUTOINCREMENT",
    postgres: "BIGSERIAL PRIMARY KEY",
    sqlserver: "BIGINT IDENTITY(1,1) PRIMARY KEY",
    mysql: "BIGINT AUTO_INCREMENT PRIMARY KEY",
    oracle: "NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY",
  },
  uuid: {
    sqlite: "TEXT PRIMARY KEY",
    postgres: "UUID PRIMARY KEY DEFAULT gen_random_uuid()",
    sqlserver: "UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID()",
    mysql: "CHAR(36) PRIMARY KEY DEFAULT (UUID())",
    oracle: "VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL PRIMARY KEY",
  },
  string: {
    sqlite: "VARCHAR(64) NOT NULL PRIMARY KEY",
    postgres: "VARCHAR(64) NOT NULL PRIMARY KEY",
    sqlserver: "NVARCHAR(64) NOT NULL PRIMARY KEY",
    mysql: "VARCHAR(64) NOT NULL PRIMARY KEY",
    oracle: "VARCHAR2(64) NOT NULL PRIMARY KEY",
  },
};

const UUID_COLUMN_SUFFIX: Record<SqlDialect, string> = {
  sqlite: "VARCHAR(36) NOT NULL UNIQUE",
  postgres: "UUID NOT NULL UNIQUE DEFAULT gen_random_uuid()",
  sqlserver: "UNIQUEIDENTIFIER NOT NULL UNIQUE DEFAULT NEWID()",
  mysql: "VARCHAR(36) NOT NULL UNIQUE DEFAULT (UUID())",
  oracle: "VARCHAR2(36) DEFAULT SYS_GUID() NOT NULL UNIQUE",
};

const UUID_DEFAULT_EXPR: Partial<Record<SqlDialect, string>> = {
  postgres: "gen_random_uuid()",
  sqlserver: "NEWID()",
  mysql: "(UUID())",
  oracle: "SYS_GUID()",
};

const TIMESTAMP_DEFAULT: Record<SqlDialect, string> = {
  sqlite: "(strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))",
  postgres: "(NOW() AT TIME ZONE 'UTC')",
  sqlserver: "GETUTCDATE()",
  mysql: "(UTC_TIMESTAMP(3))",
  oracle: "SYS_EXTRACT_UTC(SYSTIMESTAMP)",
};

const entityUsesOcc = (
  table: NormalizedTable,
  globalFlag: boolean,
): boolean => {
  if (table.datasourceType === "many-to-many") return false;
  if (table.datasourceType === "readonly-lookup") return false;
  if (table.optimisticConcurrency !== undefined) {
    return table.optimisticConcurrency;
  }
  return globalFlag === true;
};

const tableHasAuditColumns = (
  table: NormalizedTable,
  useOptimisticConcurrency: boolean,
): boolean => {
  if (table.datasourceType === "readonly-lookup") return false;
  const hasCustomPk = table.fields.some((f) => f.primaryKey && f.name !== "id");
  const occ = entityUsesOcc(table, useOptimisticConcurrency);
  if (hasCustomPk && occ) return true;
  if (hasCustomPk) return false;
  return true;
};

const columnDefForField = (
  dialect: SqlDialect,
  field: NormalizedField,
): string => {
  const type = mapColumnType(dialect, field);
  const parts = [`${q(dialect, field.name)} ${type}`];
  if (!field.isNullable) parts.push("NOT NULL");
  if (field.isUnique) parts.push("UNIQUE");
  if (field.primaryKey) parts.push("PRIMARY KEY");
  const def = renderSqlDefault(converterFor(dialect), field);
  if (def !== null) parts.push(`DEFAULT ${def}`);
  else if (field.name === "uuid") {
    const uuidDef = UUID_DEFAULT_EXPR[dialect];
    if (uuidDef) parts.push(`DEFAULT ${uuidDef}`);
  }
  return parts.join(" ");
};

export const normalizeTable = (
  entry: RawTableEntry,
  opts: GenerateTableOptions = {},
): NormalizedTable => {
  const pluralize = opts.pluralizeTableNames === true;
  const [name, def] = Object.entries(entry)[0];
  const fields = def.fields.map((fieldEntry) => {
    const [fieldName, fieldDef] = Object.entries(fieldEntry)[0];
    return {
      name: fieldName,
      type: fieldDef.type as string,
      size: fieldDef.size,
      isNullable: fieldDef.is_nullable === true,
      isUnique: fieldDef.is_unique === true,
      defaultValue: fieldDef.default_value,
      references: fieldDef.references,
      primaryKey: fieldDef.primary_key === true,
    };
  });
  return {
    name: effectiveTableName(name, pluralize),
    entityName: name,
    pluralizeTableNames: pluralize,
    datasourceType: def.datasource_type,
    optimisticConcurrency:
      def.use_optimistic_concurrency === undefined
        ? undefined
        : def.use_optimistic_concurrency === true,
    fields,
  };
};

export const generateCreateTable = (
  dialect: SqlDialect,
  table: NormalizedTable,
  opts: GenerateTableOptions = {},
): string => {
  const idType = opts.idType ?? "integer";
  const withUuidColumn = opts.withUuidColumn ?? true;
  const withAudit = tableHasAuditColumns(
    table,
    opts.useOptimisticConcurrency === true,
  );
  const lines: string[] = [];
  if (!table.fields.some((f) => f.primaryKey)) {
    const suffix = ID_COLUMN_SUFFIX[idType]?.[dialect];
    if (suffix) lines.push(`${q(dialect, "id")} ${suffix}`);
  }
  if (withUuidColumn && withAudit && !table.fields.some((f) => f.name === "uuid")) {
    lines.push(`${q(dialect, "uuid")} ${UUID_COLUMN_SUFFIX[dialect]}`);
  }
  for (const field of table.fields) {
    lines.push(columnDefForField(dialect, field));
  }
  if (withAudit) {
    const tsType = mapColumnType(dialect, { type: "datetime" });
    for (const name of ["created", "updated"] as const) {
      lines.push(
        `${q(dialect, name)} ${tsType} NOT NULL DEFAULT ${TIMESTAMP_DEFAULT[dialect]}`,
      );
    }
  }
  const body = lines.map((line) => `  ${line}`).join(",\n");
  return `CREATE TABLE ${q(dialect, table.name)} (\n${body}\n);`;
};
